In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from scipy.stats import norm
from sklearn.preprocessing import StandardScaler
from scipy import stats
import warnings

In [2]:
parent_directory = '.'

In [3]:
drop_met_cols = ['dew_point_temperature_set_1_Fahrenheit', 'wind_gust_set_1_Miles/hour', 'weather_cond_code_set_1_code',
                'cloud_layer_3_code_set_1_code', 'precip_accum_one_hour_set_1_Inches', 'precip_accum_three_hour_set_1_Inches', 
                'cloud_layer_1_code_set_1_code', 'cloud_layer_2_code_set_1_code', 'precip_accum_six_hour_set_1_Inches', 
                 'precip_accum_24_hour_set_1_Inches', 'visibility_set_1_Statute miles', 'metar_remark_set_1_text', 'metar_set_1_text',
                'air_temp_high_6_hour_set_1_Fahrenheit', 'ceiling_set_1_Feet', 'air_temp_high_24_hour_set_1_Fahrenheit', 'air_temp_low_24_hour_set_1_Fahrenheit',
                'dew_point_temperature_set_1d_Fahrenheit', 'wind_chill_set_1d_Fahrenheit', 'pressure_set_1d_INHG',
                'sea_level_pressure_set_1d_INHG', 'heat_index_set_1d_Fahrenheit', 'air_temp_low_6_hour_set_1_Fahrenheit']

In [13]:
def get_met_per_year(year):
    df_meteorological = pd.DataFrame()
    for i in range(1,13):
        if year == 2018 and i == 12:
            continue
        print('month ===> ' + str(i))
        df_met_read = pd.read_csv(parent_directory + '/meterological_data/' + str(year) + '/' + str(i) + '.csv', skiprows=[0,1,2,3,4,5], header = [0,1], error_bad_lines=False)
        df_met_read.columns = df_met_read.columns.map('_'.join)
        df_meteorological = pd.concat([df_meteorological, df_met_read])

    df_meteorological['Date_Time_Unnamed: 1_level_1'] = pd.to_datetime(df_meteorological['Date_Time_Unnamed: 1_level_1'])
    df_meteorological.index = df_meteorological['Date_Time_Unnamed: 1_level_1']
    df_meteorological_daily = df_meteorological.resample('1D').median()
    df_meteorological_daily = df_meteorological_daily.drop(columns = drop_met_cols, errors = 'ignore')
    return df_meteorological_daily

In [14]:
final_dataset_met = pd.DataFrame()
for year in range(2009,2019):
    print(year)
    df_temp_dataset = get_met_per_year(year)
    final_dataset_met = pd.concat([final_dataset_met, df_temp_dataset])

2009
month ===> 1
month ===> 2
month ===> 3
month ===> 4
month ===> 5
month ===> 6
month ===> 7
month ===> 8
month ===> 9
month ===> 10
month ===> 11
month ===> 12
2010
month ===> 1
month ===> 2
month ===> 3
month ===> 4
month ===> 5
month ===> 6
month ===> 7
month ===> 8
month ===> 9
month ===> 10
month ===> 11
month ===> 12
2011
month ===> 1
month ===> 2
month ===> 3
month ===> 4
month ===> 5
month ===> 6
month ===> 7
month ===> 8
month ===> 9
month ===> 10

b'Skipping line 1962: expected 32 fields, saw 33\nSkipping line 1963: expected 32 fields, saw 33\n'
b'Skipping line 208: expected 32 fields, saw 33\n'

month ===> 11
month ===> 12
2012
month ===> 1
month ===> 2
month ===> 3
month ===> 4
month ===> 5
month ===> 6
month ===> 7
month ===> 8
month ===> 9

b'Skipping line 38: expected 32 fields, saw 33\n'
b'Skipping line 547: expected 32 fields, saw 33\n'
b'Skipping line 921: expected 32 fields, saw 33\nSkipping line 922: expected 32 fields, saw 33\nSkipping line 1585: expected 32 fields, saw 33\n'

month ===> 10
month ===> 11
month ===> 12
2013
month ===> 1
month ===> 2
month ===> 3
month ===> 4
month ===> 5
month ===> 6
month ===> 7
month ===> 8
month ===> 9

b'Skipping line 2013: expected 32 fields, saw 33\nSkipping line 2038: expected 32 fields, saw 33\n'
b'Skipping line 1536: expected 32 fields, saw 33\nSkipping line 1538: expected 32 fields, saw 33\n'
b'Skipping line 622: expected 32 fields, saw 33\nSkipping line 1258: expected 32 fields, saw 33\n'
b'Skipping line 1936: expected 32 fields, saw 33\nSkipping line 1937: expected 32 fields, saw 33\n'
b'Skipping line 851: expected 32 fields, saw 33\n'
b'Skipping line 523: expected 32 fields, saw 33\n'
b'Skipping line 2195: expected 32 fields, saw 33\n'
b'Skipping line 1349: expected 32 fields, saw 33\nSkipping line 1351: expected 32 fields, saw 33\nSkipping line 1352: expected 32 fields, saw 33\nSkipping line 1353: expected 32 fields, saw 33\nSkipping line 1354: expected 32 fields, saw 33\n'

month ===> 10
month ===> 11
month ===> 12

b'Skipping line 190: expected 32 fields, saw 33\nSkipping line 197: expected 32 fields, saw 33\n'

2014
month ===> 1
month ===> 2
month ===> 3
month ===> 4
month ===> 5
month ===> 6
month ===> 7
month ===> 8
month ===> 9
month ===> 10

b'Skipping line 1968: expected 32 fields, saw 33\n'
b'Skipping line 1313: expected 32 fields, saw 33\nSkipping line 1314: expected 32 fields, saw 33\nSkipping line 1315: expected 32 fields, saw 33\n'
b'Skipping line 43: expected 32 fields, saw 33\n'
b'Skipping line 1459: expected 32 fields, saw 33\n'

month ===> 11
month ===> 12
2015
month ===> 1
month ===> 2
month ===> 3
month ===> 4
month ===> 5
month ===> 6
month ===> 7
month ===> 8
month ===> 9

b'Skipping line 538: expected 32 fields, saw 33\nSkipping line 539: expected 32 fields, saw 33\nSkipping line 540: expected 32 fields, saw 33\nSkipping line 542: expected 32 fields, saw 33\nSkipping line 543: expected 32 fields, saw 33\nSkipping line 547: expected 32 fields, saw 33\nSkipping line 549: expected 32 fields, saw 33\nSkipping line 604: expected 32 fields, saw 33\nSkipping line 618: expected 32 fields, saw 33\nSkipping line 621: expected 32 fields, saw 33\nSkipping line 625: expected 32 fields, saw 33\n'
b'Skipping line 323: expected 32 fields, saw 33\n'

month ===> 10
month ===> 11
month ===> 12
2016
month ===> 1
month ===> 2
month ===> 3
month ===> 4
month ===> 5
month ===> 6
month ===> 7
month ===> 8
month ===> 9

b'Skipping line 157: expected 32 fields, saw 33\nSkipping line 159: expected 32 fields, saw 33\n'
b'Skipping line 82: expected 32 fields, saw 33\nSkipping line 83: expected 32 fields, saw 33\nSkipping line 826: expected 32 fields, saw 33\nSkipping line 829: expected 32 fields, saw 33\n'
b'Skipping line 1257: expected 32 fields, saw 33\nSkipping line 1264: expected 32 fields, saw 33\nSkipping line 1265: expected 32 fields, saw 33\nSkipping line 1266: expected 32 fields, saw 33\nSkipping line 1267: expected 32 fields, saw 33\nSkipping line 1268: expected 32 fields, saw 33\nSkipping line 1274: expected 32 fields, saw 33\nSkipping line 1974: expected 32 fields, saw 33\nSkipping line 2120: expected 32 fields, saw 33\n'

month ===> 10
month ===> 11
month ===> 12
2017
month ===> 1
month ===> 2
month ===> 3
month ===> 4
month ===> 5
month ===> 6
month ===> 7
month ===> 8
month ===> 9

b'Skipping line 1157: expected 32 fields, saw 33\n'
b'Skipping line 463: expected 32 fields, saw 33\nSkipping line 464: expected 32 fields, saw 33\nSkipping line 465: expected 32 fields, saw 33\nSkipping line 466: expected 32 fields, saw 33\nSkipping line 1681: expected 32 fields, saw 33\nSkipping line 1684: expected 32 fields, saw 33\nSkipping line 1689: expected 32 fields, saw 33\nSkipping line 1694: expected 32 fields, saw 33\nSkipping line 1695: expected 32 fields, saw 33\nSkipping line 1696: expected 32 fields, saw 33\nSkipping line 1698: expected 32 fields, saw 33\n'
b'Skipping line 1391: expected 32 fields, saw 33\nSkipping line 1392: expected 32 fields, saw 33\n'
b'Skipping line 1398: expected 32 fields, saw 33\nSkipping line 2092: expected 32 fields, saw 33\n'
b'Skipping line 2061: expected 32 fields, saw 33\n'

month ===> 10
month ===> 11
month ===> 12

b'Skipping line 341: expected 32 fields, saw 33\nSkipping line 342: expected 32 fields, saw 33\nSkipping line 343: expected 32 fields, saw 33\nSkipping line 347: expected 32 fields, saw 33\n'

2018
month ===> 1
month ===> 2
month ===> 3
month ===> 4
month ===> 5
month ===> 6
month ===> 7
month ===> 8

b'Skipping line 189: expected 32 fields, saw 33\nSkipping line 218: expected 32 fields, saw 33\nSkipping line 220: expected 32 fields, saw 33\nSkipping line 222: expected 32 fields, saw 33\n'
b'Skipping line 823: expected 32 fields, saw 33\nSkipping line 824: expected 32 fields, saw 33\nSkipping line 848: expected 32 fields, saw 33\nSkipping line 849: expected 32 fields, saw 33\nSkipping line 876: expected 32 fields, saw 33\nSkipping line 884: expected 32 fields, saw 33\nSkipping line 1010: expected 32 fields, saw 33\nSkipping line 1013: expected 32 fields, saw 33\nSkipping line 1463: expected 32 fields, saw 33\nSkipping line 1464: expected 32 fields, saw 33\nSkipping line 1465: expected 32 fields, saw 33\n'
b'Skipping line 682: expected 32 fields, saw 33\n'
b'Skipping line 310: expected 32 fields, saw 33\n'
b'Skipping line 1806: expected 32 fields, saw 33\n'
b'Skipping line 373: expected 32 fields, saw 33\n'

month ===> 9
month ===> 10
month ===> 11

In [15]:
final_dataset_met.shape

(3611, 5)

In [16]:
final_dataset.shape

(3520, 2)

In [17]:
final_dataset

            Daily Max 8-hour CO Concentration  DAILY_AQI_VALUE
Date
2009-01-01                                0.3              3.0
2009-01-02                                0.3              3.0
2009-01-03                                0.3              3.0
2009-01-04                                0.3              3.0
2009-01-05                                0.3              3.0
2009-01-06                                0.5              6.0
2009-01-07                                0.4              5.0
2009-01-08                                0.3              3.0
2009-01-09                                0.4              5.0
2009-01-10                                0.2              2.0
2009-01-11                                0.3              3.0
2009-01-12                                0.4              5.0
2009-01-13                                0.4              NaN
2009-01-14                                0.4              5.0
2009-01-15                                0.3              3.0
2009-01-16                                0.3              3.0
2009-01-17                                0.3              3.0
2009-01-18                                0.3              3.0
2009-01-19                                0.3              3.0
2009-01-20                                0.3              3.0
2009-01-21                                0.3              3.0
2009-01-22                                0.5              6.0
2009-01-23                                0.5              6.0
2009-01-24                                0.3              3.0
2009-01-25                                0.3              3.0
2009-01-26                                0.4              5.0
2009-01-27                                0.4              5.0
2009-01-28                                0.3              3.0
2009-01-29                                0.2              2.0
2009-01-30                                0.3              3.0
...                                       ...              ...
2018-09-02                                0.1              1.0
2018-09-03                                0.2              2.0
2018-09-04                                0.2              2.0
2018-09-05                                0.2              2.0
2018-09-06                                0.2              2.0
2018-09-07                                0.2              2.0
2018-09-08                                0.2              2.0
2018-09-09                                0.1              1.0
2018-09-10                                0.2              2.0
2018-09-11                                0.3              3.0
2018-09-12                                0.3              3.0
2018-09-13                                0.2              2.0
2018-09-14                                0.3              3.0
2018-09-15                                0.4              5.0
2018-09-16                                0.3              3.0
2018-09-17                                0.4              5.0
2018-09-18                                0.3              3.0
2018-09-19                                0.2              2.0
2018-09-20                                0.3              3.0
2018-09-21                                0.2              2.0
2018-09-22                                0.2              2.0
2018-09-23                                0.4              5.0
2018-09-24                                0.3              3.0
2018-09-25                                0.2              2.0
2018-09-26                                0.2              2.0
2018-09-27                                0.3              3.0
2018-09-28                                0.2              2.0
2018-09-29                                0.2              2.0
2018-09-30                                0.2              2.0
2018-10-01                                0.2              2.0

[3520 rows x 2 columns]

In [22]:
final_dataset_met.isnull().sum()

altimeter_set_1_INHG            0
air_temp_set_1_Fahrenheit       0
relative_humidity_set_1_%       0
wind_speed_set_1_Miles/hour     0
wind_direction_set_1_Degrees    0
dtype: int64

In [20]:
final_dataset_met = final_dataset_met.ffill()

In [21]:
final_dataset_met

,altimeter_set_1_INHG,air_temp_set_1_Fahrenheit,relative_humidity_set_1_%,wind_speed_set_1_Miles/hour,wind_direction_set_1_Degrees
Date_Time_Unnamed: 1_level_1,,,,,
2009-01-01,29.510,21.20,68.340,11.500,180.0
2009-01-02,29.160,28.40,68.780,10.360,240.0
2009-01-03,29.370,23.00,68.110,6.910,90.0
2009-01-04,29.240,37.40,83.390,12.660,160.0
2009-01-05,29.605,20.30,61.790,6.910,265.0
2009-01-06,29.150,21.20,78.940,3.440,90.0
2009-01-07,28.685,28.40,92.850,4.610,250.0
2009-01-08,29.050,15.80,78.440,11.500,270.0
2009-01-09,29.360,17.60,78.940,5.750,110.0
2009-01-10,29.370,28.40,86.150,10.360,50.0
2009-01-11,29.470,21.20,79.580,5.750,260.0
2009-01-12,29.460,21.20,79.260,5.750,225.0
2009-01-13,29.310,19.40,79.100,12.660,310.0
2009-01-14,29.425,5.00,77.570,6.910,120.0
2009-01-15,29.835,-4.00,58.600,11.500,300.0
2009-01-16,30.000,-13.00,68.590,8.050,260.0
2009-01-17,29.415,12.20,67.765,16.110,190.0
2009-01-18,29.130,17.60,66.950,9.790,280.0
2009-01-19,29.150,15.80,78.610,8.050,310.0
2009-01-20,29.335,17.60,78.770,5.180,310.0
2009-01-21,29.370,14.00,78.440,9.220,220.0
2009-01-22,29.250,21.20,82.365,5.750,210.0
2009-01-23,29.175,30.20,80.115,8.050,250.0
2009-01-24,29.755,14.00,55.725,9.220,310.0
2009-01-25,29.710,3.20,60.030,6.910,260.0
2009-01-26,29.760,8.60,60.580,3.440,240.0
2009-01-27,29.770,15.80,61.790,0.000,0.0
2009-01-28,29.300,19.40,73.060,6.910,245.0
2009-01-29,29.235,19.40,78.440,12.660,220.0
2009-01-30,29.360,16.70,66.710,11.500,280.0
...,...,...,...,...,...
2018-10-22,30.080,41.27,58.250,5.750,220.0
2018-10-23,30.195,46.67,58.560,6.910,265.0
2018-10-24,30.390,37.67,83.925,0.000,0.0
2018-10-25,30.230,38.66,78.445,0.000,0.0
2018-10-26,29.880,44.51,68.370,4.610,60.0
2018-10-27,29.830,47.84,72.510,3.440,10.0
2018-10-28,29.760,46.94,88.960,9.220,210.0
2018-10-29,30.030,45.77,81.565,5.750,270.0
2018-10-30,29.960,47.57,71.495,6.910,150.0
2018-10-31,29.870,52.07,81.610,5.750,85.0
2018-11-01,29.870,48.92,71.000,6.330,35.0
2018-11-02,29.840,44.69,72.015,6.910,295.0
2018-11-03,30.045,40.55,82.930,0.000,0.0
2018-11-04,30.095,47.66,82.595,13.800,130.0
2018-11-05,29.885,47.66,88.250,10.360,210.0
2018-11-06,29.640,47.39,86.320,15.540,240.0
2018-11-07,30.040,37.58,67.730,14.970,270.0
2018-11-08,30.330,34.52,68.060,5.750,280.0
2018-11-09,30.130,32.54,75.190,4.610,105.0
2018-11-10,30.295,24.26,59.260,12.660,280.0
2018-11-11,30.290,28.31,68.850,8.050,190.0
2018-11-12,30.300,32.00,76.685,4.025,185.0
2018-11-13,30.365,25.79,61.395,9.220,320.0
2018-11-14,30.520,22.10,66.465,3.440,260.0
2018-11-15,30.175,29.39,81.445,5.180,90.0
2018-11-16,29.930,31.64,82.255,10.360,250.0
2018-11-17,30.220,33.98,89.170,4.610,40.0
2018-11-18,30.275,32.99,91.720,3.440,80.0
2018-11-19,30.130,27.41,90.720,4.610,220.0
2018-11-20,30.100,32.00,78.250,8.050,320.0

In [23]:
final_dataset_met.to_csv('meteorological_dataset.csv', sep=',', index=True)