In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from scipy.stats import norm
from sklearn.preprocessing import StandardScaler
from scipy import stats
import warnings

In [2]:
parent_directory = '.'

In [3]:
#pollutant_files = ['CO_illinois', 'NO2_illinois', 'OZ_illinois', 'PM10_illinois','PM25_illinois','SO2_illinois']

pollutant = 'SO2_illinois'

drop_met_cols = ['dew_point_temperature_set_1_Fahrenheit', 'wind_gust_set_1_Miles/hour', 'weather_cond_code_set_1_code',
                'cloud_layer_3_code_set_1_code', 'precip_accum_one_hour_set_1_Inches', 'precip_accum_three_hour_set_1_Inches', 
                'cloud_layer_1_code_set_1_code', 'cloud_layer_2_code_set_1_code', 'precip_accum_six_hour_set_1_Inches', 
                 'precip_accum_24_hour_set_1_Inches', 'visibility_set_1_Statute miles', 'metar_remark_set_1_text', 'metar_set_1_text',
                'air_temp_high_6_hour_set_1_Fahrenheit', 'ceiling_set_1_Feet', 'air_temp_high_24_hour_set_1_Fahrenheit', 'air_temp_low_24_hour_set_1_Fahrenheit',
                'dew_point_temperature_set_1d_Fahrenheit', 'wind_chill_set_1d_Fahrenheit', 'pressure_set_1d_INHG',
                'sea_level_pressure_set_1d_INHG', 'heat_index_set_1d_Fahrenheit', 'air_temp_low_6_hour_set_1_Fahrenheit']

drop_pol_cols = ['AQS_SITE_ID', 'POC','UNITS', 'DAILY_OBS_COUNT', 'PERCENT_COMPLETE',
       'AQS_PARAMETER_CODE', 'AQS_PARAMETER_DESC', 'CBSA_CODE', 'CBSA_NAME',
       'STATE_CODE', 'STATE', 'COUNTY_CODE', 'COUNTY', 'SITE_LATITUDE',
       'SITE_LONGITUDE']

In [4]:
def get_dataset_per_year(year):
    df_pollutant = pd.read_csv(parent_directory + '/pollutant_data/' + str(year) + '/' + pollutant + '.csv')
    df_pollutant = df_pollutant.drop(columns = drop_pol_cols, errors = 'ignore')
    df_pollutant['Date'] = pd.to_datetime(df_pollutant['Date'])
    df_pollutant.index = df_pollutant['Date']
    df_pollutant = df_pollutant.drop(columns = 'Date')
    df_pollutant_Daily = df_pollutant.resample('1D').mean()
    return df_pollutant_Daily

In [5]:
final_dataset_pol = pd.DataFrame()
for year in range(2009,2019):
    print(year)
    df_temp_dataset = get_dataset_per_year(year)
    final_dataset_pol = pd.concat([final_dataset_pol, df_temp_dataset])

2009
2010
2011
2012
2013
2014
2015
2016
2017
2018

In [6]:
final_dataset_pol

            Daily Max 1-hour SO2 Concentration  DAILY_AQI_VALUE
Date
2009-01-01                                7.10             10.0
2009-01-02                                1.10              1.5
2009-01-03                                2.30              3.0
2009-01-04                                1.60              2.0
2009-01-05                                3.35              4.5
2009-01-06                                4.60              6.5
2009-01-07                                2.55              3.5
2009-01-08                                2.80              3.5
2009-01-09                                4.75              6.5
2009-01-10                                5.45              7.0
2009-01-11                                2.10              2.5
2009-01-12                                8.00             11.5
2009-01-13                                3.50              5.0
2009-01-14                                5.20              7.5
2009-01-15                                3.80              5.0
2009-01-16                               25.85             36.5
2009-01-17                                6.95              9.5
2009-01-18                                3.45              4.5
2009-01-19                                3.15              4.0
2009-01-20                                8.60             12.0
2009-01-21                                3.35              4.5
2009-01-22                                3.95              5.0
2009-01-23                                5.80              8.0
2009-01-24                                2.30              3.0
2009-01-25                                3.10              4.5
2009-01-26                                2.20              2.5
2009-01-27                                5.35              7.5
2009-01-28                                6.05              8.5
2009-01-29                                3.95              5.0
2009-01-30                                3.15              4.0
...                                        ...              ...
2018-09-01                                0.40              0.0
2018-09-02                                0.50              0.0
2018-09-03                                0.40              0.0
2018-09-04                                0.70              0.0
2018-09-05                                0.70              0.0
2018-09-06                                0.30              0.0
2018-09-07                                0.40              0.0
2018-09-08                                0.30              0.0
2018-09-09                                0.30              0.0
2018-09-10                                0.40              0.0
2018-09-11                                1.30              1.0
2018-09-12                                1.00              1.0
2018-09-13                                1.70              1.0
2018-09-14                                1.80              1.0
2018-09-15                                0.90              0.0
2018-09-16                                1.40              1.0
2018-09-17                                1.20              1.0
2018-09-18                                0.60              0.0
2018-09-19                                0.50              0.0
2018-09-20                                1.00              1.0
2018-09-21                                 NaN              NaN
2018-09-22                                 NaN              NaN
2018-09-23                                 NaN              NaN
2018-09-24                                 NaN              NaN
2018-09-25                                 NaN              NaN
2018-09-26                               -1.20              0.0
2018-09-27                                 NaN              NaN
2018-09-28                                0.50              0.0
2018-09-29                                0.40              0.0
2018-09-30                                0.30              0.0

[3432 rows x 2 columns]

In [7]:
final_dataset_pol['ffill'] = final_dataset_pol['Daily Max 1-hour SO2 Concentration'].ffill()

In [8]:
final_dataset_pol['bfill'] = final_dataset_pol['Daily Max 1-hour SO2 Concentration'].bfill()

In [9]:
final_dataset_pol['Daily Max 1-hour SO2 Concentration'] = final_dataset_pol[['ffill', 'bfill']].mean(axis=1)

In [10]:
final_dataset_pol = final_dataset_pol.drop(['ffill', 'bfill'], axis=1)

In [11]:
final_dataset_pol

            Daily Max 1-hour SO2 Concentration  DAILY_AQI_VALUE
Date
2009-01-01                                7.10             10.0
2009-01-02                                1.10              1.5
2009-01-03                                2.30              3.0
2009-01-04                                1.60              2.0
2009-01-05                                3.35              4.5
2009-01-06                                4.60              6.5
2009-01-07                                2.55              3.5
2009-01-08                                2.80              3.5
2009-01-09                                4.75              6.5
2009-01-10                                5.45              7.0
2009-01-11                                2.10              2.5
2009-01-12                                8.00             11.5
2009-01-13                                3.50              5.0
2009-01-14                                5.20              7.5
2009-01-15                                3.80              5.0
2009-01-16                               25.85             36.5
2009-01-17                                6.95              9.5
2009-01-18                                3.45              4.5
2009-01-19                                3.15              4.0
2009-01-20                                8.60             12.0
2009-01-21                                3.35              4.5
2009-01-22                                3.95              5.0
2009-01-23                                5.80              8.0
2009-01-24                                2.30              3.0
2009-01-25                                3.10              4.5
2009-01-26                                2.20              2.5
2009-01-27                                5.35              7.5
2009-01-28                                6.05              8.5
2009-01-29                                3.95              5.0
2009-01-30                                3.15              4.0
...                                        ...              ...
2018-09-01                                0.40              0.0
2018-09-02                                0.50              0.0
2018-09-03                                0.40              0.0
2018-09-04                                0.70              0.0
2018-09-05                                0.70              0.0
2018-09-06                                0.30              0.0
2018-09-07                                0.40              0.0
2018-09-08                                0.30              0.0
2018-09-09                                0.30              0.0
2018-09-10                                0.40              0.0
2018-09-11                                1.30              1.0
2018-09-12                                1.00              1.0
2018-09-13                                1.70              1.0
2018-09-14                                1.80              1.0
2018-09-15                                0.90              0.0
2018-09-16                                1.40              1.0
2018-09-17                                1.20              1.0
2018-09-18                                0.60              0.0
2018-09-19                                0.50              0.0
2018-09-20                                1.00              1.0
2018-09-21                               -0.10              NaN
2018-09-22                               -0.10              NaN
2018-09-23                               -0.10              NaN
2018-09-24                               -0.10              NaN
2018-09-25                               -0.10              NaN
2018-09-26                               -1.20              0.0
2018-09-27                               -0.35              NaN
2018-09-28                                0.50              0.0
2018-09-29                                0.40              0.0
2018-09-30                                0.30              0.0

[3432 rows x 2 columns]

In [12]:
final_dataset_met = pd.read_csv(parent_directory + '/meteorological_dataset.csv')

In [13]:
final_dataset_met.shape

(3611, 6)

In [14]:
final_dataset_pol.shape

(3432, 2)

In [15]:
final_dataset_met.isnull().sum()

Date_Time_Unnamed: 1_level_1    0
altimeter_set_1_INHG            0
air_temp_set_1_Fahrenheit       0
relative_humidity_set_1_%       0
wind_speed_set_1_Miles/hour     0
wind_direction_set_1_Degrees    0
dtype: int64

In [16]:
final_dataset_pol.isnull().sum()

Daily Max 1-hour SO2 Concentration      0
DAILY_AQI_VALUE                       408
dtype: int64

In [17]:
final_dataset_met

,Date_Time_Unnamed: 1_level_1,altimeter_set_1_INHG,air_temp_set_1_Fahrenheit,relative_humidity_set_1_%,wind_speed_set_1_Miles/hour,wind_direction_set_1_Degrees
0,2009-01-01,29.510,21.20,68.340,11.500,180.0
1,2009-01-02,29.160,28.40,68.780,10.360,240.0
2,2009-01-03,29.370,23.00,68.110,6.910,90.0
3,2009-01-04,29.240,37.40,83.390,12.660,160.0
4,2009-01-05,29.605,20.30,61.790,6.910,265.0
5,2009-01-06,29.150,21.20,78.940,3.440,90.0
6,2009-01-07,28.685,28.40,92.850,4.610,250.0
7,2009-01-08,29.050,15.80,78.440,11.500,270.0
8,2009-01-09,29.360,17.60,78.940,5.750,110.0
9,2009-01-10,29.370,28.40,86.150,10.360,50.0
10,2009-01-11,29.470,21.20,79.580,5.750,260.0
11,2009-01-12,29.460,21.20,79.260,5.750,225.0
12,2009-01-13,29.310,19.40,79.100,12.660,310.0
13,2009-01-14,29.425,5.00,77.570,6.910,120.0
14,2009-01-15,29.835,-4.00,58.600,11.500,300.0
15,2009-01-16,30.000,-13.00,68.590,8.050,260.0
16,2009-01-17,29.415,12.20,67.765,16.110,190.0
17,2009-01-18,29.130,17.60,66.950,9.790,280.0
18,2009-01-19,29.150,15.80,78.610,8.050,310.0
19,2009-01-20,29.335,17.60,78.770,5.180,310.0
20,2009-01-21,29.370,14.00,78.440,9.220,220.0
21,2009-01-22,29.250,21.20,82.365,5.750,210.0
22,2009-01-23,29.175,30.20,80.115,8.050,250.0
23,2009-01-24,29.755,14.00,55.725,9.220,310.0
24,2009-01-25,29.710,3.20,60.030,6.910,260.0
25,2009-01-26,29.760,8.60,60.580,3.440,240.0
26,2009-01-27,29.770,15.80,61.790,0.000,0.0
27,2009-01-28,29.300,19.40,73.060,6.910,245.0
28,2009-01-29,29.235,19.40,78.440,12.660,220.0
29,2009-01-30,29.360,16.70,66.710,11.500,280.0
...,...,...,...,...,...,...
3581,2018-10-22,30.080,41.27,58.250,5.750,220.0
3582,2018-10-23,30.195,46.67,58.560,6.910,265.0
3583,2018-10-24,30.390,37.67,83.925,0.000,0.0
3584,2018-10-25,30.230,38.66,78.445,0.000,0.0
3585,2018-10-26,29.880,44.51,68.370,4.610,60.0
3586,2018-10-27,29.830,47.84,72.510,3.440,10.0
3587,2018-10-28,29.760,46.94,88.960,9.220,210.0
3588,2018-10-29,30.030,45.77,81.565,5.750,270.0
3589,2018-10-30,29.960,47.57,71.495,6.910,150.0
3590,2018-10-31,29.870,52.07,81.610,5.750,85.0
3591,2018-11-01,29.870,48.92,71.000,6.330,35.0
3592,2018-11-02,29.840,44.69,72.015,6.910,295.0
3593,2018-11-03,30.045,40.55,82.930,0.000,0.0
3594,2018-11-04,30.095,47.66,82.595,13.800,130.0
3595,2018-11-05,29.885,47.66,88.250,10.360,210.0
3596,2018-11-06,29.640,47.39,86.320,15.540,240.0
3597,2018-11-07,30.040,37.58,67.730,14.970,270.0
3598,2018-11-08,30.330,34.52,68.060,5.750,280.0
3599,2018-11-09,30.130,32.54,75.190,4.610,105.0
3600,2018-11-10,30.295,24.26,59.260,12.660,280.0
3601,2018-11-11,30.290,28.31,68.850,8.050,190.0
3602,2018-11-12,30.300,32.00,76.685,4.025,185.0
3603,2018-11-13,30.365,25.79,61.395,9.220,320.0
3604,2018-11-14,30.520,22.10,66.465,3.440,260.0
3605,2018-11-15,30.175,29.39,81.445,5.180,90.0
3606,2018-11-16,29.930,31.64,82.255,10.360,250.0
3607,2018-11-17,30.220,33.98,89.170,4.610,40.0
3608,2018-11-18,30.275,32.99,91.720,3.440,80.0
3609,2018-11-19,30.130,27.41,90.720,4.610,220.0
3610,2018-11-20,30.100,32.00,78.250,8.050,320.0

In [18]:
final_dataset_met['Date_Time_Unnamed: 1_level_1'] = pd.to_datetime(final_dataset_met['Date_Time_Unnamed: 1_level_1'])
final_dataset_met.index = final_dataset_met['Date_Time_Unnamed: 1_level_1']
final_dataset_met = final_dataset_met.drop(['Date_Time_Unnamed: 1_level_1'], axis = 1)

In [19]:
final_dataset_met.head()

,altimeter_set_1_INHG,air_temp_set_1_Fahrenheit,relative_humidity_set_1_%,wind_speed_set_1_Miles/hour,wind_direction_set_1_Degrees
Date_Time_Unnamed: 1_level_1,,,,,
2009-01-01,29.510,21.2,68.34,11.50,180.0
2009-01-02,29.160,28.4,68.78,10.36,240.0
2009-01-03,29.370,23.0,68.11,6.91,90.0
2009-01-04,29.240,37.4,83.39,12.66,160.0
2009-01-05,29.605,20.3,61.79,6.91,265.0

In [20]:
final_dataset = final_dataset_pol.join(final_dataset_met, how = 'inner')

In [21]:
final_dataset.shape

(3432, 7)

In [22]:
final_dataset

,Daily Max 1-hour SO2 Concentration,DAILY_AQI_VALUE,altimeter_set_1_INHG,air_temp_set_1_Fahrenheit,relative_humidity_set_1_%,wind_speed_set_1_Miles/hour,wind_direction_set_1_Degrees
2009-01-01,7.10,10.0,29.510,21.20,68.340,11.500,180.0
2009-01-02,1.10,1.5,29.160,28.40,68.780,10.360,240.0
2009-01-03,2.30,3.0,29.370,23.00,68.110,6.910,90.0
2009-01-04,1.60,2.0,29.240,37.40,83.390,12.660,160.0
2009-01-05,3.35,4.5,29.605,20.30,61.790,6.910,265.0
2009-01-06,4.60,6.5,29.150,21.20,78.940,3.440,90.0
2009-01-07,2.55,3.5,28.685,28.40,92.850,4.610,250.0
2009-01-08,2.80,3.5,29.050,15.80,78.440,11.500,270.0
2009-01-09,4.75,6.5,29.360,17.60,78.940,5.750,110.0
2009-01-10,5.45,7.0,29.370,28.40,86.150,10.360,50.0
2009-01-11,2.10,2.5,29.470,21.20,79.580,5.750,260.0
2009-01-12,8.00,11.5,29.460,21.20,79.260,5.750,225.0
2009-01-13,3.50,5.0,29.310,19.40,79.100,12.660,310.0
2009-01-14,5.20,7.5,29.425,5.00,77.570,6.910,120.0
2009-01-15,3.80,5.0,29.835,-4.00,58.600,11.500,300.0
2009-01-16,25.85,36.5,30.000,-13.00,68.590,8.050,260.0
2009-01-17,6.95,9.5,29.415,12.20,67.765,16.110,190.0
2009-01-18,3.45,4.5,29.130,17.60,66.950,9.790,280.0
2009-01-19,3.15,4.0,29.150,15.80,78.610,8.050,310.0
2009-01-20,8.60,12.0,29.335,17.60,78.770,5.180,310.0
2009-01-21,3.35,4.5,29.370,14.00,78.440,9.220,220.0
2009-01-22,3.95,5.0,29.250,21.20,82.365,5.750,210.0
2009-01-23,5.80,8.0,29.175,30.20,80.115,8.050,250.0
2009-01-24,2.30,3.0,29.755,14.00,55.725,9.220,310.0
2009-01-25,3.10,4.5,29.710,3.20,60.030,6.910,260.0
2009-01-26,2.20,2.5,29.760,8.60,60.580,3.440,240.0
2009-01-27,5.35,7.5,29.770,15.80,61.790,0.000,0.0
2009-01-28,6.05,8.5,29.300,19.40,73.060,6.910,245.0
2009-01-29,3.95,5.0,29.235,19.40,78.440,12.660,220.0
2009-01-30,3.15,4.0,29.360,16.70,66.710,11.500,280.0
...,...,...,...,...,...,...,...
2018-09-01,0.40,0.0,30.020,71.60,88.460,9.220,190.0
2018-09-02,0.50,0.0,30.050,76.91,79.650,9.220,200.0
2018-09-03,0.40,0.0,30.165,75.56,80.080,5.750,180.0
2018-09-04,0.70,0.0,30.190,72.41,89.265,5.750,160.0
2018-09-05,0.70,0.0,30.110,78.17,71.355,8.050,200.0
2018-09-06,0.30,0.0,30.250,69.80,88.905,8.050,30.0
2018-09-07,0.40,0.0,30.230,67.19,84.680,8.050,40.0
2018-09-08,0.30,0.0,30.160,63.50,71.270,10.360,50.0
2018-09-09,0.30,0.0,30.050,61.97,68.275,12.660,40.0
2018-09-10,0.40,0.0,30.010,62.33,74.820,8.050,40.0
2018-09-11,1.30,1.0,30.130,61.88,86.895,0.000,0.0
2018-09-12,1.00,1.0,30.180,66.02,72.855,3.440,90.0
2018-09-13,1.70,1.0,30.190,65.93,76.300,4.025,50.0
2018-09-14,1.80,1.0,30.140,66.47,75.410,0.000,0.0
2018-09-15,0.90,0.0,30.160,70.79,71.285,0.000,0.0
2018-09-16,1.40,1.0,30.120,70.25,80.955,4.610,40.0
2018-09-17,1.20,1.0,29.965,73.13,75.425,3.440,50.0
2018-09-18,0.60,0.0,29.940,70.16,85.070,3.440,10.0
2018-09-19,0.50,0.0,30.010,68.27,85.025,5.750,40.0
2018-09-20,1.00,1.0,29.970,69.80,89.395,5.750,165.0
2018-09-21,-0.10,NaN,29.855,75.20,60.000,13.800,225.0
2018-09-22,-0.10,NaN,30.260,59.90,59.010,9.220,60.0
2018-09-23,-0.10,NaN,30.180,56.03,78.715,3.440,40.0
2018-09-24,-0.10,NaN,30.100,60.98,83.730,6.910,110.0
2018-09-25,-0.10,NaN,29.910,69.62,90.130,5.750,190.0
2018-09-26,-1.20,0.0,30.085,62.60,76.785,8.050,290.0
2018-09-27,-0.35,NaN,30.120,54.14,74.800,0.000,0.0
2018-09-28,0.50,0.0,30.040,54.68,70.170,6.910,230.0
2018-09-29,0.40,0.0,30.310,49.10,80.130,3.440,50.0
2018-09-30,0.30,0.0,30.200,54.41,68.495,5.750,85.0

In [23]:
final_dataset.to_csv('AQI_dataset_SO2.csv', sep=',', index=True)